### DISCUSSION TITLE
doubleclick left mousebutton does a resize within vertical sidebar -- option to change to "new tab" instead?

### DISCUSSION THREAD

**Discussion by Rawh** [Floorp-Projects/Floorp#1606] [Feature Request]
Greetings,

Been trying to find if there was a setting for this to emulate behavior I have come to love from the "tree tab" addon in Firefox. 

When you double click with the left mouse button on an empty space in the sidebar, it resizes floorp. I would like to have it create / open a new tab for you to use. 

Could this be implemented as an option to configure? I have attempted to use userChrome.css to alter the default behavior of the sidebar in floorp but as there is no universal documented id or class, I cannot effective target and alter the behavior. I have tried it with the following code but without any success

```css
#sidebar-box, .sidebar-panel {
    resize: none !important;
    pointer-events: auto !important;
}

#sidebar-box:hover {
    cursor: default !important;
}
```

Same goes with a few tampermonkey tries. It doesn't seem to understand the sidebar and instead is searching it within a website source / dom / div :(
