### DISCUSSION TITLE
2 fix and 2 features for zen browsing

### DISCUSSION THREAD

**Discussion by smir-ant** [Floorp-Projects/Floorp#1748] [Feature Request]
some features which i think will be extra top for lovers minimalism:
1️⃣ [fix] auto hide toolbar. yeap, it's done in lepton (mark Automatically hide Toolbar), but it works ugly with vertical tab bar, temp fix that i did it's
```css
#nav-bar:not([customizing]) {
  margin-bottom: calc(-1 * var(--uc-navbar-height) + 5px) !important;
}
```
(a little bit (5px) space for correct hovering) but it's a temp solution, cuz it looks like some top-padding

2️⃣ [feature] hide some elems (from my userChome)
```css
box#identity-icon-box, #tracking-protection-icon-container, #alltabs-button {
  display: none !important;
}
/* p.s. i use hotkeys (ctrl-w with ctrl-t) for control window and tabs */
#new-tab-button {
  display: none !important;
}
#tabbrowser-tabs {
  border-bottom: none !important;
}
```

3️⃣ [fix] traffic on macos (.titlebar-buttonbox) doesn't work with autohide. temp solution is hide traffic buttons and use ctrl+q
```css
hbox.titlebar-buttonbox {
  display: none !important;
  appearance: none !important;
}
```

tech:
- macos m1pro 14.4 sonoma
- floorp 11.26.2

video of my minimalism custom for better understanding and visualizations my visions

https://github.com/user-attachments/assets/a35c68c3-173c-4c72-bc9f-53ec5ea99230

4️⃣ [feature] reverse tabs order. easy to realise(?) but very glad to have option reverse order from column to column-reverse(in vertical mode or row and row-reverse in classic mode) in settings
