### DISCUSSION TITLE
Add areas to hold click and drag the window with, when vertical tabs are enabled.

### DISCUSSION THREAD

**Discussion by YousufSSyed** [Floorp-Projects/Floorp#579] [Feature Request]
In Firefox, and right now on Floorp, the only drag areas are on the bookmarks bar. I wrote this CSS to add some myself:

```css
#floorp-tabbar-window-manage-container {
  margin-right: 25px;
}
```
