### DISCUSSION TITLE
Add option to change the size of Bookmark icon.

### DISCUSSION THREAD

**Discussion by tasinone** [Floorp-Projects/Floorp#840] [Feature Request]
Hi, can you please add the option to change the size of the bookmark icon on the homepage just like the Waterfox browser? Also, please change the icon design because it is not so good-looking. Some favicons are bigger while some are small. Also, the padding around the bookmark icon is not so good looking. I hope the upcoming update will bring some UI changes.

![Screenshot_137](https://github.com/Floorp-Projects/Floorp/assets/33787196/491a97ca-05b1-41e3-9ec2-bd35b9c98b97)

 Also, the option to set the background image blur is not working. I am using Windows 10 Ghost Spector. I have manually used a blur image.

**Comment by creeper-0910** [comment]
![image](https://github.com/Floorp-Projects/Floorp/assets/56744841/6440a688-838c-443f-bf14-953ffb5a0a44)
Does it look like this?
Is the border of the icon also unnecessary?

**Reply by tasinone** [reply]
Yeah! That is what I am talking about. In this screenshot, the icons look beautiful but in my case, it is not. IDK why. Also, please let me know if I can remove the padding background color just like the screenshot below.
![Screenshot_139](https://github.com/Floorp-Projects/Floorp/assets/33787196/692dce41-be04-4c1f-a0f0-91a2977a3eae)

And is the option below supposed to blur the home's wallpaper? If yes then it is not working. I mean the background image isn't blurred even if the option is set to on.
![Screenshot_140](https://github.com/Floorp-Projects/Floorp/assets/33787196/a49fc674-fd62-457c-b651-7f6bd075cd26)

**Reply by tasinone** [reply]
I want to make it look like this. How do I access to the CSS file?
![Screenshot_141](https://github.com/Floorp-Projects/Floorp/assets/33787196/479242f8-af0b-4aa8-86e4-98e90a84c631)

**Reply by creeper-0910** [reply]
Do you want to remove the logo and search bar?

**Reply by creeper-0910** [reply]
1.Enable legacy components in the configuration.
2.Add this text to "chrome\userContent.css".
```css

  @charset "UTF-8";
  @-moz-document url-prefix("about:newtab"), url-prefix("about:home") {
    .non-collapsible-section {
      display: none !important;
    }
    .top-sites-list .top-site-outer .top-site-inner .top-site-button .tile {
      background-color: transparent !important;
    }
    .top-sites-list .top-site-outer .top-site-inner .top-site-button .tile .icon-wrapper .top-site-icon {
      background-color: transparent !important;
    }
  }

```
3.Restart Floorp.
