### DISCUSSION TITLE
Need new about:config setting for tabs

### DISCUSSION THREAD

**Discussion by Telmesomething** [Floorp-Projects/Floorp#886] [Feature Request]
Please make the following setting available in about:config: **browser.tabs.tabMaximum.Width** and set to something small like **20** for example. These ridiculously wide tabs take up too much tab space on the tab bar when using a laptop with a small screen. I tried creating it myself using "Number" in about:config, but it doesn't make any difference. 

Also, having narrower tabs would go some way to hiding the annoying chrome//browser tab which launches on startup. I often forget to close that first before enabling a Floorp tab (the one with a Floorp logo). Launching a site with the chrome//browser tab means there's no back button which will work to reopen a closed tab. Here's a pix of what I mean in case somebody doesn't understand what I'm referring to.

![chrome browser tab](https://github.com/Floorp-Projects/Floorp/assets/33827636/c92a707c-2788-466e-aa4d-7b209b42e817)

**Comment by rguhr** [comment]
Currently the maximum can be set to 60px via UI under about:hub#/features/design > Tabs

Using `userChrome.css` you can go even smaller, e.g.:

```css

:root {
  --my-tab-min-width: 30px;
}

/* Essential rule for reducing minimum tab width */
.tabbrowser-tab:not([pinned]){
  min-width: var(--my-tab-min-width) !important;
}

/* Optional rules for widths below 40px */
/* Reduce icon's right margin for less wasted space */
.tabbrowser-tab:not([pinned]) .tab-icon-image {
  margin-right: 5px !important;
}
/* Adjust padding for better centering and less wasted space */
.tabbrowser-tab:not([pinned]) .tab-content{
  padding-left: calc((var(--my-tab-min-width) - 22px)/2) !important;
  padding-right: calc((var(--my-tab-min-width) - 22px)/2) !important;
}

/* Hide Close button on tabs */
.tab-close-button {
    display: none !important;
}
```
