### ISSUE TITLE
[Bug]: `Hide the Bookmarks Toolbar unless hovering over the navigation bar` triggers BMBar appearance too early.

### ISSUE THREAD

**Issue by guigirl42** [Floorp-Projects/Floorp#1097]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have tried to create a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [ ] I have checked this problem is not ocurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

`Hide the Bookmarks Toolbar unless hovering over the navigation bar` triggers BMBar appearance too early, obstructing important page items. 

When attempting [by slowly moving the pointer upwards from within the page] to access the page control icons at the top of some website or AddOn pages, access is actually impossible because several pixels before reaching the target, the BM Bar appears, entirely obstructing access. 

### Reproduction Steps

1. Enable Floorp's `Hide the Bookmarks Toolbar unless hovering over the navigation bar` setting
2. With the mouse pointer initially somewhere far below the BM Bar [BMB], move the pointer upwards approaching the top of the page
3. Observe that _before_ reaching the top of the page the BMB suddenly appears, thus completely obstructing all page content now behind the BMB
4. If the page has no important data in that region, this is not a practical problem
5. On the other hand, all pages with important data in that band, which rely on the user being able to interact by clicking on page elements therein, are now practically unusable
6. Try again but this time moving down from above the page
7. Observe that the same problem recurs

### Expected Behavior

Ideally the BMB appearing should not be triggered until the pointer crosses the interface between the URL-bar & the _top_ of the BMB. Unfortunately atm the trigger seems to be the page position at the _bottom_ of the BMB. 

### Actual Behavior

_Before_ reaching the top of the page the BMB suddenly appears, thus completely obstructing all page content now behind the BMB.

### Screenshots

Pic-1: Mouse pointer is far away from the position where it triggers the automatic appearance of the BM Bar, hence all the important page control icons / options are _ostensibly_ available for access [green outline].
![image](https://github.com/Floorp-Projects/Floorp/assets/76090786/87a997fb-5fa4-4c12-9a16-306660d750fc)

Pic-2: When attempting [by slowly moving the pointer upwards from within the page] to access the page control icons [in this case the tick-mark to mark the item as read], access is actually impossible because several pixels before reaching the target, the BM Bar appears, entirely obstructing access. 
![image](https://github.com/Floorp-Projects/Floorp/assets/76090786/b4dcdbf2-30a7-4ebc-8941-06f469421952)

### Browser Version

11.12.0

### Operating System

ArchLinux KDEPlasma Wayland.

### Additional Context

Until this bug is solved, i'm working around it by disabling the Floorp setting, & instead using this CSS [that i also use in my Firefox Nightly] in my `userChrome.css`:

https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_bookmarks_toolbar.css

**Comment by anotherwanwanyi** [comment]
Same issue here.

After some research, I found a possible solution.

The question seems to be related to the `z-index` property of the element in the [bookmarkbar_autohide.css](https://github.com/Floorp-Projects/Floorp-core/blob/main/browser/themes/designs/options/bookmarkbar_autohide.css) file.

File's content:

```CSS
#PersonalToolbar {
   position: relative !important;
   margin-bottom: -28px;
   opacity: 0 !important;
   transition: all 125ms !important;
   z-index: 1 !important;
}

#navigator-toolbox:hover > #PersonalToolbar {
   transition: all 200ms !important;
   transition-delay: 0.2s !important;
   opacity: 1 !important;
}
```

My solution is to move the `z-index: 1 !important` declaration from the `#PersonalToolbar` rule to the `#navigator-toolbox:hover > #PersonalToolbar` rule.

In my opinion, the `z-index: 1 !important` on the `#PersonalToolbar` rule is constantly placing the toolbar on top of the webpage's content, which may be causing this issue.

In addition, if you want the bookmark auto-hide feature provided by Floorp without this issue, you can simply disable Floorp's setting and add the following to your userChrome.css:

```CSS
#PersonalToolbar {
    position: relative !important;
    margin-bottom: -28px;
    opacity: 0 !important;
    transition: all 125ms !important;
}

#navigator-toolbox:hover > #PersonalToolbar {
    transition: all 200ms !important;
    transition-delay: 0.2s !important;
    opacity: 1 !important;
    z-index: 1 !important;
}
```

**Comment by TheChilledBuffalo** [comment]
@anotherwanwanyi 

That does seem to work! Thank you. Do you want to send a PR for it? Here's the file: https://github.com/Floorp-Projects/Floorp-core/blob/main/browser/themes/designs/options/bookmarkbar_autohide.css

**Comment by anotherwanwanyi** [comment]
@TheChilledBuffalo 

My solution will only fix this specific issue.

However, there is another issue that needs to be addressed.

If you have the vertical tabs setting enabled, you'll notice that the vertical tabs are on top of the bookmark bar, which can sometimes cause disruptions.

In the browser's Developer Tools, the vertical tabs is a toolbar with the ID "TabsToolbar".

You can find its CSS code in the file [native-verticaltab-hover.css](https://github.com/Floorp-Projects/Floorp-core/blob/main/browser/themes/designs/options/native-verticaltab-hover.css):

```CSS
#TabsToolbar {
  width: var(--default-verticaltab-width) !important;
  transition: all 200ms !important;
  transition-delay: 0.2s !important;
  z-index: 100 !important;
  background-repeat: no-repeat !important;
  background-position: center center !important;
  background-size: cover !important;
}
```

Here, the `#TabsToolbar` is defined with `z-index: 100 !important`, which is much higher than 1.

I found that I can't simply set the `z-index` of `#navigator-toolbox:hover > #PersonalToolbar` to 101 to solve this issue, as this would cause the bookmark bar to be on top of the address bar's search results.

I think the key is understanding the reason why `#TabsToolbar`'s `z-index` is set to 100.
However, I'm not familiar with Floorp. Perhaps someone with more experience working with Floorp could investigate this further and offer a solution.

BTW, in my testing, setting `#TabsToolbar`'s `z-index` to 1 while setting `#navigator-toolbox:hover > #PersonalToolbar`'s `z-index` to 2 seems to resolve this issue.

**Comment by TheChilledBuffalo** [comment]
@anotherwanwanyi 

> the vertical tabs are on top of the bookmark bar

Yup I had just seen that while looking at this issue. But, thank you bringing it to my attention.

> I think the key is understanding the reason why #TabsToolbar's z-index is set to 100.

To be honest, that value needn't be set to 100. It was used as a precaution just in case some other element gets displayed over it. If that needs to be changed to fix this issue, then go for it.

**Comment by Radrahil** [comment]
I also have this issue. The BM Bar appears way faster than before, and it's really annoying. Is there anything I can do in the browser settings to stop this apart from CTRL Shift B?

**Comment by anotherwanwanyi** [comment]
Hi, has anyone tested this in Fullscreen mode?

I find this bug also happens when my browser in Fullscreen mode.

The code I used to resolve this bug may be a bit dirty, but it works for me:

```CSS
:root[inFullscreen]
#PersonalToolbar {
    margin-bottom: 0px;
    margin-top: -36px;
}

:root[inFullscreen]
#navigator-toolbox:hover > #PersonalToolbar {
    margin-top: 0px;
    transition: all 0ms !important;
    transition-delay: 0s !important;
}
```

Note that `margin-top` is set to -36px because the height of my bookmark bar is 36px...
I'm not sure if this -36px value would be suitable for everyone.
