### ISSUE TITLE
[Feature Request] Consider re-add verticaltab collapsing  option

### ISSUE THREAD

**Issue by toooonyy** [Floorp-Projects/Floorp#524]
### Attention!

- [X] I understand that Floorp is NOT supported on Windows 7/8.1 or lower.

### Describe the bug

In Floorp 11.4.1, vertical tab can be auto collapsed. After upgrading to 11.5 it won't anymore. Or maybe I overlook any options?

### To Reproduce

No relevant.

### Expected behavior

When mouse is near the tab bar, everything is collapsed like this pic.  
![Screenshot 2023-10-23 at 12 44 35](https://github.com/Floorp-Projects/Floorp/assets/3480434/5c676d10-7fa0-415b-9d0c-01b2a21a4ae8)
When I move mouse on, it should auto expand to certain(maybe even adjustable) amount.
![Screenshot 2023-10-23 at 12 45 45](https://github.com/Floorp-Projects/Floorp/assets/3480434/560fa877-bae0-4aa7-83e1-7fca53e28c82)

### OS Info

macOS 14

### Floorp Version

15.0

### Additional context

After downgrading to 11.4.1, I confirmed it worked before. Maybe the refactor of vertical tab breaks something.

**Comment by surapunoyousei** [comment]
OK. Try to re-add the option.

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp-core/commit/b3bc1c570e8e85b6f8086e4d9b8fd9b2fc2d9aa3

Added.

Browser maintenance is not easy. Especially if it is a feature-oriented Floorp.

Currently, I am the only one maintaining Floorp, and with almost no contributors, such deletions could happen at any time. Please keep this in mind.

**Comment by roskelld** [comment]
If anyone has instructions for how to work around this, I would love to know. I don't know anything about editing userChrome.css or where to find the option to add it back in.

**Comment by surapunoyousei** [comment]
```css
/*-- This Source Code Form is subject to the terms of the Mozilla Public
   - License, v. 2.0. If a copy of the MPL was not distributed with this
   - file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#TabsToolbar {
  max-width: none !important;
  min-width: 0px !important;
}
  
#verticaltab-splitter {
  display: none !important;
}
  
/*shared*/
#TabsToolbar-customization-target {
  position: relative !important;
  clip-path: inset(0) !important;
  z-index: 1 !important;
  transition-delay: 0.2s !important;
}
  
:root {
  --default-vertitaltab-width: 45px;
  --hoverd-verticaltab-width: 20em;
}

:root[uidensity=compact]{
  --default-vertitaltab-width: 35px !important;
}

:root[uidensity=touch]{
  --default-vertitaltab-width: 60px !important;
}
  
/*close*/
#TabsToolbar {
  --hovering-verticaltab-width: calc( var(--default-vertitaltab-width) + 12px);
  width: var(--default-vertitaltab-width) !important;
  transition-delay: 0.2s !important;
}

#TabsToolbar:not(:hover) #tabbrowser-tabs[closebuttons="activetab"] .tabbrowser-tab:not([visuallyselected]) .tab-content[class] > .tab-close-button[class] {
  display: none !important;
  visibility: hidden !important;
}

#TabsToolbar:not(:hover) #tabbrowser-tabs[closebuttons="activetab"] .tabbrowser-tab .tab-content[class] > .tab-close-button[class] {
  display: none !important;
  visibility: hidden !important;
}

#TabsToolbar:not(:hover) .tab-label-container {
  display: none !important;
}

#TabsToolbar:not(:hover) #TabsToolbar-customization-target > .toolbarbutton-1 > .toolbarbutton-text {
  display: none !important;
}

#TabsToolbar:not(:hover) .tab-icon-stack {
  padding-left: 10px;
}

#TabsToolbar:not(:hover) .tab-content {
  --inline-tab-padding:0px !important;
  padding-inline: 0px !important;
}

#sidebar-box .tabbrowser-tab{
  margin-right: 1px !important;
  margin-left: 1px !important;
}
  
/*open*/
#TabsToolbar:hover {
  --hovering-verticaltab-width: var(--hoverd-verticaltab-width) !important; 
  transition: all 200ms !important;
  transition-delay: 0.2s !important;
  z-index: 100 !important;
  width: 250px !important;
}
  
/*left*/
#TabsToolbar:not([positionend="true"]):hover {
  margin-right: calc((var(--hoverd-verticaltab-width) - var(--default-vertitaltab-width) + 10px) * -1) !important;
}
  
/*right*/
#TabsToolbar[positionend="true"]:hover {
  margin-left: calc((var(--hoverd-verticaltab-width) - var(--default-vertitaltab-width) + 10px) * -1) !important;
}
  
/* if tab doesn't have an icon, make sure it still has tab icon */

.tab-icon-image:not([src], [busy]) {
  width: 16px !important;
  height: 16px !important;
  display: inherit !important;
}

#tabbrowser-tabs[positionpinnedtabs] > #tabbrowser-arrowscrollbox > .tabbrowser-tab[pinned] {
  min-width: -moz-available !important;
}

.tab-icon-stack[pinned="true"] {
  margin-inline-end: 5.5px;
}

.tab-label-container[pinned="true"][flex] {
  display: inherit !important;
}

:root[uidensity] .tabbrowser-tab[context][class], .tabbrowser-tab[context][class] {
  min-width: -moz-available !important;
}
```
